project_id = "apoeceltgnvohsbxfopb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[edge_functions]
enabled = true

[functions.openai-chat-robust]
verify_jwt = true

[functions.openai-text-analysis-robust]
verify_jwt = true

[functions.immigration-forms-manager]
verify_jwt = true

[functions.ai-agent-chat]
verify_jwt = true

[functions.ai-assistant-chat]
verify_jwt = true

[functions.ai-job-processor]
verify_jwt = true

[functions.ai-job-queue]
verify_jwt = true

[functions.visa-recommendation]
verify_jwt = false

[functions.webhook-handler]
verify_jwt = false

[functions.workflow-executor]
verify_jwt = true

[functions.ai-test-agent]
verify_jwt = true

[functions.analyze-form-responses]
verify_jwt = true

[functions.data-cleanup]
verify_jwt = true

[functions.document-analysis]
verify_jwt = true

[functions.error-logger]
verify_jwt = true

[functions.generate-intelligent-form]
verify_jwt = false

[functions.generate-official-forms]
verify_jwt = true

[functions.immigration-assistant]
verify_jwt = false

[functions.info-logger]
verify_jwt = true

[functions.public-api]
verify_jwt = false

[functions.realtime-metrics]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.smart-case-analysis]
verify_jwt = true

[functions.translate-form-responses]
verify_jwt = true

[functions.policy-rules-collector]
verify_jwt = true

[functions.uscis-monitor]
verify_jwt = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"