# ConfigMap for OSPREY application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: osprey-config
  namespace: osprey-production
data:
  # Application configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  DEBUG: "false"
  
  # Database configuration
  MONGO_DB: "osprey_immigration"
  
  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  DEFAULT_RATE_LIMIT: "60"
  
  # File upload
  MAX_FILE_SIZE: "10485760"
  UPLOAD_DIR: "/app/uploads"
  
  # CORS
  CORS_ORIGINS: "https://osprey.com,https://app.osprey.com"
  
  # JWT
  JWT_ALGORITHM: "HS256"

---
# ConfigMap for nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: osprey-production
data:
  nginx.conf: |
    # Nginx configuration file content would go here
    # (This would be the same as the nginx.conf file we created)
    
---
# ConfigMap for monitoring configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: osprey-production
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # "first_rules.yml"
      # "second_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'osprey-backend'
        static_configs:
          - targets: ['osprey-backend-service:8001']
        metrics_path: '/api/metrics'
        
      - job_name: 'osprey-frontend'
        static_configs:
          - targets: ['osprey-frontend-service:3000']